name: "PR - Test Docker Build"

# This workflow builds a docker image for every pull request, to
# confirm that the changes will still at least build even if the
# OP has not tried it themselves or configured their fork to use
# the included repos

on:
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - 
            uses: actions/checkout@v3
            
        # Build Docker image with Buildx
        # https://github.com/docker/build-push-action
        -
            name: Build and push Docker image
            id: build-and-push
            uses: docker/build-push-action@v3
            with:
                push: false
                context: .
                platforms: linux/amd64,linux/arm64,linux/arm/v7
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/automatic-ripping-machine:pr${{ github.event.number }}
